### ISSUE TITLE
Crash on new install open application

### ISSUE THREAD

**Issue by naresh1283** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#118]
Hello,
  I am using Branch-1.8.4.jar with my project. When I installed my app from the play store (alpha testing version) and try to open the first time, the app crashed. I checked the logs and saw below crash logs.

More info:
The params I passed when creating a branch referral url
branch.getReferralUrl("android-app", null, new Branch.BranchLinkCreateListener() { }
But I think this has nothing to do with the crash, since I have installed the app by searching in Play Store , not by clicking the referral link generated by the app.

Crash Logs:
    java.lang.RuntimeException: Unable to start receiver io.branch.referral.InstallListener: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2586)
            at android.app.ActivityThread.access$1700(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at io.branch.referral.InstallListener.onReceive(SourceFile:39)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2579)
            at android.app.ActivityThread.access$1700(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by sojanpr** [comment]
@naresh1283  We are really sorry for the issue. Thanks for reaching out. We have already fixed this issue and will be releasing soon.

**Comment by naresh1283** [comment]
@sojanpr , could you clarify whether this crash can happen for every first time opening the app on a fresh install from google play store? If that is the case, I have to wait to publish my app until this fix is released in the Branch.jar.

**Comment by sojanpr** [comment]
@naresh1283 
 First of all we  have  fixed this issue and released version v1.8.5. I would recommend you to update to this version.
  This crash won't happen every time you install from play store. This is happened with a really weird situation where the application got the referrer information in a wrong format.

**Comment by naresh1283** [comment]
@sojanpr Thanks a lot. Cheers.
