### ISSUE TITLE
Library crash after branch.io link is clicked and app launched

### ISSUE THREAD

**Issue by lepipele** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#227]
It's truly weird bug - has to do with favicon and SSL library your are using - you may want to add additional try/catch there. Here is log:

```
03-30 14:50:04.659 29496-29496/com.xxxxx.xxxxxxxx.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.xxxxx.xxxxxxxx.dev, PID: 29496
                                                                        java.lang.NullPointerException
                                                                            at io.branch.referral.Branch.readAndStripParam(Branch.java:1232)
                                                                            at io.branch.referral.Branch.initSession(Branch.java:815)
                                                                            at com.xxxxx.xxxxxxxx.activities.MainActivity.handleIntent(MainActivity.java:197)
                                                                            at com.xxxxx.xxxxxxxx.activities.MainActivity.onNewIntent(MainActivity.java:162)
                                                                            at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1167)
                                                                            at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2569)
                                                                            at android.app.ActivityThread.performNewIntents(ActivityThread.java:2582)
                                                                            at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2591)
                                                                            at android.app.ActivityThread.access$1700(ActivityThread.java:171)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:146)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5679)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                            at dalvik.system.NativeStart.main(Native Method)
03-30 14:50:05.049 25602-25728/? E/LoadFaviconTask: Error reading favicon
                                                    javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x82c78e18: Failure in SSL library, usually a protocol error
                                                    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x740187e8:0x00000000)
                                                        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:469)
                                                        at ch.boye.httpclientandroidlib.conn.ssl.SSLSocketFactory.connectSocket$4028dcbe(SSLSocketFactory.java:535)
                                                        at ch.boye.httpclientandroidlib.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
                                                        at ch.boye.httpclientandroidlib.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
                                                        at ch.boye.httpclientandroidlib.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
                                                        at ch.boye.httpclientandroidlib.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
                                                        at ch.boye.httpclientandroidlib.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
                                                        at ch.boye.httpclientandroidlib.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:825)
                                                        at ch.boye.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
                                                        at ch.boye.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
                                                        at org.mozilla.gecko.favicons.LoadFaviconTask.tryDownloadRecurse(LoadFaviconTask.java:132)
                                                        at org.mozilla.gecko.favicons.LoadFaviconTask.downloadAndDecodeImage(LoadFaviconTask.java:249)
                                                        at org.mozilla.gecko.favicons.LoadFaviconTask.downloadFavicon(LoadFaviconTask.java:226)
                                                        at org.mozilla.gecko.favicons.LoadFaviconTask.doInBackground(LoadFaviconTask.java:439)
                                                        at org.mozilla.gecko.favicons.LoadFaviconTask$1.run(LoadFaviconTask.java:308)
                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                        at java.lang.Thread.run(Thread.java:841)
                                                     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x82c78e18: Failure in SSL library, usually a protocol error
                                                    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x740187e8:0x00000000)
                                                        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:426)
                                                        	... 17 more
```

**Comment by sojanpr** [comment]
@lepipele Sorry that you are facing this issue. We are working it and  update you asap

**Comment by sojanpr** [comment]
@lepipele  Thanks for reporting this . We have added  a PR for the NPE protection https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/issues/227

The error from Favicon or SSL lib are not directly related  with Branch. We don't use them with our SDK.
It is weird that your Activity's intent URI data is set to null some how. 
Do you set the Intent data anywhere in you application? 
Do you have any libs added to your project that manipulate  Activity intents

**Comment by lepipele** [comment]
I will look into how giving you exact steps to reproduce the problem - it has to do with going to branch URL with Firefox. Looking at the log the day after it's possible that first error was thrown by you (Url == null) and second was thrown by Firefox.

Thanks for your prompt response!
