### ISSUE TITLE
ConcurrentModification Crash from ServerRequestQueue:81

### ISSUE THREAD

**Issue by manas-chaudhari** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#234]
Steps to reproduce are unknown, however we are receiving a lot of crash reports.

Branch library version: 
**v1.10.2**

Stacktrace:
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:792)
       at java.util.HashMap$EntryIterator.next(HashMap.java:829)
       at java.util.HashMap$EntryIterator.next(HashMap.java:827)
       at org.json.JSONObject.writeTo(JSONObject.java:666)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONObject.writeTo(JSONObject.java:667)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONArray.writeTo(JSONArray.java:572)
       at org.json.JSONArray.toString(JSONArray.java:544)
       at io.branch.referral.ServerRequestQueue$1.run(ServerRequestQueue.java:81)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by sojanpr** [comment]
@manas-chaudhari Sorry to see that you are having this issue. This was a corner case bug with v1.10.2 and v1.10.3 .The fix is added to v1.10.4.
